# -- NETWORK --
networks:
  public_net:
    driver: bridge
  internal_net:
    driver: bridge

services:
  # --- REVERSE PROXY ---
  traefik:
    image: traefik:v3.6
    environment:
      - DOCKER_API_VERSION=1.45
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAILSECURE}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      # Observability 
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/acme.json:/acme.json
      - ./proxy/dynamic:/dynamic:ro
    networks:
      - public_net
      - internal_net
  # --- GESTÃO VISUAL DE CONTÊINERES ---
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    networks:
      - public_net
      - internal_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`painel.${DOMINIO}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
